# Generated by Django 3.0.5 on 2020-04-20 08:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f96ca945-401b-4b61-8ce2-aa60eebe36af'), primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='主机名')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('account', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('platform', models.CharField(choices=[('Centos', 'Centos'), ('Windows', 'Windows')], max_length=128, verbose_name='操作系统')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk_info', models.CharField(blank=True, max_length=1024, null=True, verbose_name='硬盘')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU')),
                ('created_by', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建人')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('share_users', models.ManyToManyField(blank=True, related_name='machines', to='User.Users', verbose_name='分配用户')),
            ],
        ),
    ]
